In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
# Axis: 0 for column wise and 1 for Row-wise
cal = A.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [9]:
percentage = 100*A/cal
# 100*A/cal.reshape(1,4)
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [19]:
a = np.array([[-0.0967311, -2.38617377, -0.3243588, -0.96216349, 0.54410384]]).reshape(5,1)
a

array([[-0.0967311 ],
       [-2.38617377],
       [-0.3243588 ],
       [-0.96216349],
       [ 0.54410384]])

In [22]:
a.shape
a.T

array([[-0.0967311 , -2.38617377, -0.3243588 , -0.96216349,  0.54410384]])

In [21]:
print(np.dot(a, a.T))

[[ 0.00935691  0.23081721  0.03137558  0.09307113 -0.05263176]
 [ 0.23081721  5.69382526  0.77397646  2.29588928 -1.29832631]
 [ 0.03137558  0.77397646  0.10520863  0.3120862  -0.17648487]
 [ 0.09307113  2.29588928  0.3120862   0.92575858 -0.52351685]
 [-0.05263176 -1.29832631 -0.17648487 -0.52351685  0.29604899]]
